version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - ./database/dev:/var/lib/mysql
    networks:
      - coodesh-app-dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: coodesh-api:dev
    depends_on:
      - mysql
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_HOST=mysql
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - coodesh-app-dev

networks:
  coodesh-app-dev:
    driver: bridge